# Use the official Golang image as a base
FROM golang:1.20

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the working directory
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the entire project directory to the working directory
COPY . .

# Build the Go application
RUN go build -o main ./cmd

# Expose the port the application will run on
EXPOSE 50051

# Run the application
CMD ["./main"]
